### ISSUE TITLE
Binder error 

### ISSUE THREAD

**Issue by prajwalmani** [ccsc-tools/RNN-CME-prediction#1]
### Error 
**TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.**

This error is even caused when the code is run on the local system too

### Suggestion to solve the error
Either protobuf is not the correct version or the protobuf package is missing
This can be solved by using **"pip install protobuf==3.20.3"**

**Comment by ya54** [comment]
Yes, the newer version is having issues.

Please add the package with the working  version to environment.yml and requirement.txt using  branch,  create pull request and I will approve it.

Make sure it works.

Thanks.
